<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>storm rule</name>
  <uuid>a72346d1-172a-49e6-a651-9de06d0691c8</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	Weather is storm alert
    
then
	set decision to "Stay home! This is a storm alert!" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
