<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>94fe258d-316e-4c9a-9f1d-75e80146371f</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to "Please provide a name!" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
